server:
  port: 9988

minio:
  url: http://127.0.0.1:9000
  user: admin
  password: admin123
  bucketName: test

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  groovy:
    template:
      cache: false
  # 全局日期时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haohao.minio.domain
  global-config:
    banner: false
    db-config:
      # 主键生成策略
      id-type: auto
      # 逻辑删除
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 可以更新null值
      update-strategy: ignored