server:
  port: 9988

minio:
  url: http://127.0.0.1:9000
  user: admin
  password: admin123
  bucketName: test

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  groovy:
    template:
      cache: false