server:
  port: 9982
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update